//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CKS.Dev.WCT.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CKS.Dev.WCT.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error removing existing File nodes from {0}, file may contain additional incorrect entries after import: {1}.
        /// </summary>
        internal static string String_Errors_CorrectFileNodes {
            get {
                return ResourceManager.GetString("String_Errors_CorrectFileNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target solution file failed to copy: {0}.
        /// </summary>
        internal static string String_Errors_TargetSolutionFileNotFound {
            get {
                return ResourceManager.GetString("String_Errors_TargetSolutionFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Model of WSPBuilder Project....
        /// </summary>
        internal static string String_LogMessages_BuildingSourceModel {
            get {
                return ResourceManager.GetString("String_LogMessages_BuildingSourceModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements have been split into individual SharePoint Items, but associated class files will not have been moved..
        /// </summary>
        internal static string String_LogMessages_ClassFilesNotMoved {
            get {
                return ResourceManager.GetString("String_LogMessages_ClassFilesNotMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} features imported successfully..
        /// </summary>
        internal static string String_LogMessages_FeaturesMapped {
            get {
                return ResourceManager.GetString("String_LogMessages_FeaturesMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WSPBuilder project import completed successfully..
        /// </summary>
        internal static string String_LogMessages_ImportCompleteSuccess {
            get {
                return ResourceManager.GetString("String_LogMessages_ImportCompleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing {0}: {1}....
        /// </summary>
        internal static string String_LogMessages_ImportingFeature {
            get {
                return ResourceManager.GetString("String_LogMessages_ImportingFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrading Project to Visual Studio 2010....
        /// </summary>
        internal static string String_LogMessages_MappingTarget {
            get {
                return ResourceManager.GetString("String_LogMessages_MappingTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed....
        /// </summary>
        internal static string String_LogMessages_ProjectCompleted {
            get {
                return ResourceManager.GetString("String_LogMessages_ProjectCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not completed: {0}....
        /// </summary>
        internal static string String_LogMessages_ProjectNotCompleted {
            get {
                return ResourceManager.GetString("String_LogMessages_ProjectNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing WSPBuilder project: {0}....
        /// </summary>
        internal static string String_LogMessages_ProjectStart {
            get {
                return ResourceManager.GetString("String_LogMessages_ProjectStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing associated assemblies from source project. Safe Control entries are not added. Please add your Safe Control entries if any, manually..
        /// </summary>
        internal static string String_LogMessages_SafeControlEntries {
            get {
                return ResourceManager.GetString("String_LogMessages_SafeControlEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitting SharePoint Item {0} to folder {1}....
        /// </summary>
        internal static string String_LogMessages_SplitElementToUniqueFolder {
            get {
                return ResourceManager.GetString("String_LogMessages_SplitElementToUniqueFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitting SharePoint Item {0} from Element {1}....
        /// </summary>
        internal static string String_LogMessages_SplitSharePointItemFromElement {
            get {
                return ResourceManager.GetString("String_LogMessages_SplitSharePointItemFromElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint themes have been detected in this project. The handling of themes has been changed in SharePoint 2010. SharePoint 2007 themes can be activated in backwards compatibility mode by setting SPWeb.UIVersion = 3 and subsequently calling SPWeb.Update()..
        /// </summary>
        internal static string String_LogMessages_ThemeCodeUpdate {
            get {
                return ResourceManager.GetString("String_LogMessages_ThemeCodeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference version updated. Reference {0} updated to {1}....
        /// </summary>
        internal static string String_LogMessages_UpdateReferenceVersion {
            get {
                return ResourceManager.GetString("String_LogMessages_UpdateReferenceVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Found: {0}..
        /// </summary>
        internal static string Strings_CommandLine_FileNotFound {
            get {
                return ResourceManager.GetString("Strings_CommandLine_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source must be a CSharp project file (.csproj)..
        /// </summary>
        internal static string Strings_CommandLine_InvalidSourceCS {
            get {
                return ResourceManager.GetString("Strings_CommandLine_InvalidSourceCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source must be a Visual Basic project file (.vbproj)..
        /// </summary>
        internal static string Strings_CommandLine_InvalidSourceVB {
            get {
                return ResourceManager.GetString("Strings_CommandLine_InvalidSourceVB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project assembly is not built: {0}..
        /// </summary>
        internal static string Strings_CommandLine_NotBuilt {
            get {
                return ResourceManager.GetString("Strings_CommandLine_NotBuilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project is not a WSPBuilder project..
        /// </summary>
        internal static string Strings_CommandLine_NotVSeWSSProject {
            get {
                return ResourceManager.GetString("Strings_CommandLine_NotVSeWSSProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source does not contain WSPBuilder projects..
        /// </summary>
        internal static string Strings_CommandLine_NotVSeWSSSolution {
            get {
                return ResourceManager.GetString("Strings_CommandLine_NotVSeWSSSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WSPBuilder project must be packaged: {0}..
        /// </summary>
        internal static string Strings_CommandLine_SolutionNotPackaged {
            get {
                return ResourceManager.GetString("Strings_CommandLine_SolutionNotPackaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding associated class file {0} for SharePoint Project Item {1}: {2}.
        /// </summary>
        internal static string Strings_Errors_AddClassFile {
            get {
                return ResourceManager.GetString("Strings_Errors_AddClassFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding project file {0}: {1}.
        /// </summary>
        internal static string Strings_Errors_AddProjectFile {
            get {
                return ResourceManager.GetString("Strings_Errors_AddProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your source project contains a reference to project {0} which would previously been in the same solution. You should ensure that a reference is added, either by adding the relevant project to this solution and referencing, or by referencing the output assembly..
        /// </summary>
        internal static string Strings_Errors_AddProjectReference {
            get {
                return ResourceManager.GetString("Strings_Errors_AddProjectReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding reference {0}: {1}.
        /// </summary>
        internal static string Strings_Errors_AddReference {
            get {
                return ResourceManager.GetString("Strings_Errors_AddReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding Safe Control {0} for Custom Assembly {1} to Package: {2}.
        /// </summary>
        internal static string Strings_Errors_AddSafeControlToCustomAssembly {
            get {
                return ResourceManager.GetString("Strings_Errors_AddSafeControlToCustomAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source project contains service references. The files created by adding and updating this service reference have been imported and will build, but these should be removed and the service references re-added manually..
        /// </summary>
        internal static string Strings_Errors_AddServiceReference {
            get {
                return ResourceManager.GetString("Strings_Errors_AddServiceReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding Strong Name Key file {0}: {1}.
        /// </summary>
        internal static string Strings_Errors_AddSNKFile {
            get {
                return ResourceManager.GetString("Strings_Errors_AddSNKFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding SharePoint Project Item {0} to Feature {1}: {2}.
        /// </summary>
        internal static string Strings_Errors_AddSPIToFeature {
            get {
                return ResourceManager.GetString("Strings_Errors_AddSPIToFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source project contains web references. The files created by adding and updating this web reference have been imported and will build, but these should be removed and the web references re-added manually..
        /// </summary>
        internal static string Strings_Errors_AddWebReference {
            get {
                return ResourceManager.GetString("Strings_Errors_AddWebReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to determine LCID from {0}. WebTemp files will be placed directly in the {1} folder..
        /// </summary>
        internal static string Strings_Errors_CannotFindLCID {
            get {
                return ResourceManager.GetString("Strings_Errors_CannotFindLCID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find Site Elements Manifest for Site Definition with ID {0}.
        /// </summary>
        internal static string Strings_Errors_CannotFindSiteElementsManifest {
            get {
                return ResourceManager.GetString("Strings_Errors_CannotFindSiteElementsManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding build configurations..
        /// </summary>
        internal static string Strings_Errors_CorruptBuildConfiguration {
            get {
                return ResourceManager.GetString("Strings_Errors_CorruptBuildConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt source solution: Invalid XML in Element manifest at {0}. No SharePoint Item will be created for this element. {1}.
        /// </summary>
        internal static string Strings_Errors_CorruptSolutionElementManifestInvalidXML {
            get {
                return ResourceManager.GetString("Strings_Errors_CorruptSolutionElementManifestInvalidXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt source solution: The feature element id {0} already exists in this solution. You should consider changing the feature element id in {1}..
        /// </summary>
        internal static string Strings_Errors_CorruptSolutionFeatureElementManifestIdConflict {
            get {
                return ResourceManager.GetString("Strings_Errors_CorruptSolutionFeatureElementManifestIdConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt source solution: Invalid XML in Feature manifest at {0}. This feature will be skipped by the import process. {1}.
        /// </summary>
        internal static string Strings_Errors_CorruptSolutionFeatureManifestInvalidXML {
            get {
                return ResourceManager.GetString("Strings_Errors_CorruptSolutionFeatureManifestInvalidXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt source solution: element manifest {0} should contain an ID. An ID of {1} has been created for this element, although intended mappings may be affected..
        /// </summary>
        internal static string Strings_Errors_CorruptSolutionMissingElementId {
            get {
                return ResourceManager.GetString("Strings_Errors_CorruptSolutionMissingElementId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt source solution: Element manifest expected at {0} not found. No SharePoint Item will be created for this element..
        /// </summary>
        internal static string Strings_Errors_CorruptSolutionMissingExpectedElementManifest {
            get {
                return ResourceManager.GetString("Strings_Errors_CorruptSolutionMissingExpectedElementManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt source solution: Feature manifest expected at {0} not found. This feature will be skipped by the import process..
        /// </summary>
        internal static string Strings_Errors_CorruptSolutionMissingExpectedFeatureManifest {
            get {
                return ResourceManager.GetString("Strings_Errors_CorruptSolutionMissingExpectedFeatureManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt source solution: missing feature ID attribute in manifest at {0}. A new ID {1} has been supplied and the import of this feature will continue, but any expected mappings to other features and associated classes will be lost and SharePoint items will not be created for any expected child elements of this feature..
        /// </summary>
        internal static string Strings_Errors_CorruptSolutionMissingFeatureId {
            get {
                return ResourceManager.GetString("Strings_Errors_CorruptSolutionMissingFeatureId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt source solution: missing Feature node in manifest at {0}. This feature will be skipped by the import process and SharePoint items will not be created for any expected child elements of this feature..
        /// </summary>
        internal static string Strings_Errors_CorruptSolutionMissingFeatureNode {
            get {
                return ResourceManager.GetString("Strings_Errors_CorruptSolutionMissingFeatureNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt source solution: Root file expected at {0} not found. This file may have been linked from a different path in the source project..
        /// </summary>
        internal static string Strings_Errors_CorruptSolutionMissingRootFile {
            get {
                return ResourceManager.GetString("Strings_Errors_CorruptSolutionMissingRootFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt source solution: Schema file expected at {0} not found..
        /// </summary>
        internal static string Strings_Errors_CorruptSolutionMissingSchemaFile {
            get {
                return ResourceManager.GetString("Strings_Errors_CorruptSolutionMissingSchemaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt source solution: missing solution node..
        /// </summary>
        internal static string Strings_Errors_CorruptSolutionMissingSolutionNode {
            get {
                return ResourceManager.GetString("Strings_Errors_CorruptSolutionMissingSolutionNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt source solution: Template file expected at {0} not found. This file may have been linked from a different path in the source project..
        /// </summary>
        internal static string Strings_Errors_CorruptSolutionMissingTemplateFile {
            get {
                return ResourceManager.GetString("Strings_Errors_CorruptSolutionMissingTemplateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt source solution: Feature {0} ({1}) has more elements in it&apos;s feature manifest than are indicated in the WSP mapper file (pkg\solution.xml). Element {2} cannot be mapped to this feature. .
        /// </summary>
        internal static string Strings_Errors_CorruptSolutionNumberOfFeaturesMismatch {
            get {
                return ResourceManager.GetString("Strings_Errors_CorruptSolutionNumberOfFeaturesMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Feature has been detected that refers to Feature Receiver class {0}. Feature {1} has been created..
        /// </summary>
        internal static string Strings_Errors_CorruptSolutionOrphanedFeatureReceiverClass {
            get {
                return ResourceManager.GetString("Strings_Errors_CorruptSolutionOrphanedFeatureReceiverClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt source solution: Invalid XML in schema file at {0}. {1}.
        /// </summary>
        internal static string Strings_Errors_CorruptSolutionSchemaFileInvalidXML {
            get {
                return ResourceManager.GetString("Strings_Errors_CorruptSolutionSchemaFileInvalidXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt source solution: the WSP manifest references an element with ID {0} that does not exist in the solution. This element will be ignored by the import process..
        /// </summary>
        internal static string Strings_Errors_CorruptSolutionWSPElementNotExist {
            get {
                return ResourceManager.GetString("Strings_Errors_CorruptSolutionWSPElementNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt source solution: Feature {0} is refenced in the WSP Mapper (solution.xml) file but does not appear in the Solution Manifest. A new feature will be created as a parent for elements with the following ID&apos;s: {1} .
        /// </summary>
        internal static string Strings_Errors_CorruptSolutionWspMapperSolutionManifestInconsistency {
            get {
                return ResourceManager.GetString("Strings_Errors_CorruptSolutionWspMapperSolutionManifestInconsistency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding Custom Assembly reference for {0} to Package: {1}.
        /// </summary>
        internal static string Strings_Errors_CreateCustomAssembly {
            get {
                return ResourceManager.GetString("Strings_Errors_CreateCustomAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating element manifest {0}: {1}.
        /// </summary>
        internal static string Strings_Errors_CreateElementManifest {
            get {
                return ResourceManager.GetString("Strings_Errors_CreateElementManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating feature {0}: {1}.
        /// </summary>
        internal static string Strings_Errors_CreateFeature {
            get {
                return ResourceManager.GetString("Strings_Errors_CreateFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating Mapped Folder {0}: {1}.
        /// </summary>
        internal static string Strings_Errors_CreateMappedFolder {
            get {
                return ResourceManager.GetString("Strings_Errors_CreateMappedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding Project Item File {0} to {1}: {2}.
        /// </summary>
        internal static string Strings_Errors_CreateProjectItemFile {
            get {
                return ResourceManager.GetString("Strings_Errors_CreateProjectItemFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating SharePoint Project Item {0}: {1}.
        /// </summary>
        internal static string Strings_Errors_CreateSPI {
            get {
                return ResourceManager.GetString("Strings_Errors_CreateSPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding Safe Control {0} to {1}: {2}.
        /// </summary>
        internal static string Strings_Errors_CreateSPISafeControl {
            get {
                return ResourceManager.GetString("Strings_Errors_CreateSPISafeControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error mapping additional assembly {0}: {1}.
        /// </summary>
        internal static string Strings_Errors_MapAdditionalAssembly {
            get {
                return ResourceManager.GetString("Strings_Errors_MapAdditionalAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error mapping aspx/ascx file {0}: {1}.
        /// </summary>
        internal static string Strings_Errors_MapAspxAscxFile {
            get {
                return ResourceManager.GetString("Strings_Errors_MapAspxAscxFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error mapping element {0}: {1}.
        /// </summary>
        internal static string Strings_Errors_MapElement {
            get {
                return ResourceManager.GetString("Strings_Errors_MapElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error mapping feature {0}: {1}.
        /// </summary>
        internal static string Strings_Errors_MapFeature {
            get {
                return ResourceManager.GetString("Strings_Errors_MapFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error mapping Package Template file: {0}.
        /// </summary>
        internal static string Strings_Errors_MapPackageTemplate {
            get {
                return ResourceManager.GetString("Strings_Errors_MapPackageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error mapping root files: {0}.
        /// </summary>
        internal static string Strings_Errors_MapRootFiles {
            get {
                return ResourceManager.GetString("Strings_Errors_MapRootFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error mapping Site Definition: {0}.
        /// </summary>
        internal static string Strings_Errors_MapSiteDefinition {
            get {
                return ResourceManager.GetString("Strings_Errors_MapSiteDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error mapping template files: {0}.
        /// </summary>
        internal static string Strings_Errors_MapTemplateFiles {
            get {
                return ResourceManager.GetString("Strings_Errors_MapTemplateFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error migrating project item {0}: {1}.
        /// </summary>
        internal static string Strings_Errors_MigrateProjectItem {
            get {
                return ResourceManager.GetString("Strings_Errors_MigrateProjectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source project is missing manifest and/or solution XML..
        /// </summary>
        internal static string Strings_Errors_MissingManifestOrSolutionXml {
            get {
                return ResourceManager.GetString("Strings_Errors_MissingManifestOrSolutionXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error determining .ascx files from source project: {0}.
        /// </summary>
        internal static string Strings_Errors_ModelGetAscx {
            get {
                return ResourceManager.GetString("Strings_Errors_ModelGetAscx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error determining .aspx files from source project: {0}.
        /// </summary>
        internal static string Strings_Errors_ModelGetAspx {
            get {
                return ResourceManager.GetString("Strings_Errors_ModelGetAspx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error determining .master files from source project: {0}.
        /// </summary>
        internal static string Strings_Errors_ModelGetMaster {
            get {
                return ResourceManager.GetString("Strings_Errors_ModelGetMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error obtaining site definition ID from WSP manifest, mappings to the existing Site Elements feature may be lost: {0}.
        /// </summary>
        internal static string Strings_Errors_ObtainSiteDefinitionId {
            get {
                return ResourceManager.GetString("Strings_Errors_ObtainSiteDefinitionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error obtaining site elements ID from WSP manifest, mappings to the existing Site Elements feature may be lost: {0}.
        /// </summary>
        internal static string Strings_Errors_ObtainSiteElementsId {
            get {
                return ResourceManager.GetString("Strings_Errors_ObtainSiteElementsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing non-mapped manifest elements: {0}.
        /// </summary>
        internal static string Strings_Errors_PackageMapperGetNonMappedManifestElements {
            get {
                return ResourceManager.GetString("Strings_Errors_PackageMapperGetNonMappedManifestElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating Package Template file {0}: {1}.
        /// </summary>
        internal static string Strings_Errors_PackageTemplateFileUpdate {
            get {
                return ResourceManager.GetString("Strings_Errors_PackageTemplateFileUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing WSP mapping file..
        /// </summary>
        internal static string Strings_Errors_ParseWSPMappingFile {
            get {
                return ResourceManager.GetString("Strings_Errors_ParseWSPMappingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing List Instances for Site Definition: {0}.
        /// </summary>
        internal static string Strings_Errors_ProcessSiteDefinitionListInstance {
            get {
                return ResourceManager.GetString("Strings_Errors_ProcessSiteDefinitionListInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing Module Definitions for Site Definition: {0}.
        /// </summary>
        internal static string Strings_Errors_ProcessSiteDefinitionModule {
            get {
                return ResourceManager.GetString("Strings_Errors_ProcessSiteDefinitionModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error referencing project item {0}: {1}.
        /// </summary>
        internal static string Strings_Errors_ReferenceProjectItem {
            get {
                return ResourceManager.GetString("Strings_Errors_ReferenceProjectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating referenced assembly version in {0}: {1}.
        /// </summary>
        internal static string Strings_Errors_SetAssemblyVersion {
            get {
                return ResourceManager.GetString("Strings_Errors_SetAssemblyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting Field Control class reference in {0}: {1}.
        /// </summary>
        internal static string Strings_Errors_SetFieldControlClassReference {
            get {
                return ResourceManager.GetString("Strings_Errors_SetFieldControlClassReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating List Instance Feature ID from {0} to {1}: {2}.
        /// </summary>
        internal static string Strings_Errors_SetListInstanceFeatureId {
            get {
                return ResourceManager.GetString("Strings_Errors_SetListInstanceFeatureId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting List Instace template type for {0}: {1}.
        /// </summary>
        internal static string Strings_Errors_SetListInstanceTemplateTypes {
            get {
                return ResourceManager.GetString("Strings_Errors_SetListInstanceTemplateTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating Webpart Type Name for {0}: {1}.
        /// </summary>
        internal static string Strings_Errors_SetWebPartTypeName {
            get {
                return ResourceManager.GetString("Strings_Errors_SetWebPartTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving Aspx/Ascx file updates to {0}: {1}.
        /// </summary>
        internal static string Strings_Errors_UpdateAspxAscxFile {
            get {
                return ResourceManager.GetString("Strings_Errors_UpdateAspxAscxFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating element manifest {0}: {1}.
        /// </summary>
        internal static string Strings_Errors_UpdateElementManifest {
            get {
                return ResourceManager.GetString("Strings_Errors_UpdateElementManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving Field Type file updates to {0}: {1}.
        /// </summary>
        internal static string Strings_Errors_UpdateFieldType {
            get {
                return ResourceManager.GetString("Strings_Errors_UpdateFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving Web Part file updates to {0}: {1}.
        /// </summary>
        internal static string Strings_Errors_UpdateWebPart {
            get {
                return ResourceManager.GetString("Strings_Errors_UpdateWebPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identified assembly file at {0}..
        /// </summary>
        internal static string Strings_LogModel_IdentifyAssemblyFile {
            get {
                return ResourceManager.GetString("Strings_LogModel_IdentifyAssemblyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identified associated class {0}.{1} in {2}..
        /// </summary>
        internal static string Strings_LogModel_IdentifyAssociatedClass {
            get {
                return ResourceManager.GetString("Strings_LogModel_IdentifyAssociatedClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identified hard coded receiver assembly {0} and receiver class {1}. Since the receiver assembly reference points to the source project assembly, it will be tokenised so that it points to the current project..
        /// </summary>
        internal static string Strings_LogModel_IdentifyHardCodedReceiverClass {
            get {
                return ResourceManager.GetString("Strings_LogModel_IdentifyHardCodedReceiverClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identified hard coded receiver assembly {0} and receiver class {1}..
        /// </summary>
        internal static string Strings_LogModel_IdentifyHardCodedReceiverClassExternalAssembly {
            get {
                return ResourceManager.GetString("Strings_LogModel_IdentifyHardCodedReceiverClassExternalAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identified receiver class {0}.{1} in {2}..
        /// </summary>
        internal static string Strings_LogModel_IdentifyReceiverClass {
            get {
                return ResourceManager.GetString("Strings_LogModel_IdentifyReceiverClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identified site provisioning class {0}.{1}..
        /// </summary>
        internal static string Strings_LogModel_IdentifySiteProvisioningClass {
            get {
                return ResourceManager.GetString("Strings_LogModel_IdentifySiteProvisioningClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element manifests in the root project folder are not supported: manifest moved to {0}..
        /// </summary>
        internal static string Strings_LogModel_MoveProjectRootElementManifest {
            get {
                return ResourceManager.GetString("Strings_LogModel_MoveProjectRootElementManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing assemblies..
        /// </summary>
        internal static string Strings_LogModel_ParseAssemblies {
            get {
                return ResourceManager.GetString("Strings_LogModel_ParseAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing assembly {0}..
        /// </summary>
        internal static string Strings_LogModel_ParseAssembly {
            get {
                return ResourceManager.GetString("Strings_LogModel_ParseAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing element manifest {0}..
        /// </summary>
        internal static string Strings_LogModel_ParseElement {
            get {
                return ResourceManager.GetString("Strings_LogModel_ParseElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing element file {0}..
        /// </summary>
        internal static string Strings_LogModel_ParseElementFile {
            get {
                return ResourceManager.GetString("Strings_LogModel_ParseElementFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing element manifest {0}..
        /// </summary>
        internal static string Strings_LogModel_ParseElementManifest {
            get {
                return ResourceManager.GetString("Strings_LogModel_ParseElementManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing elements..
        /// </summary>
        internal static string Strings_LogModel_ParseElements {
            get {
                return ResourceManager.GetString("Strings_LogModel_ParseElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing feature manifest {0}..
        /// </summary>
        internal static string Strings_LogModel_ParseFeature {
            get {
                return ResourceManager.GetString("Strings_LogModel_ParseFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing features from source project..
        /// </summary>
        internal static string Strings_LogModel_ParseFeatures {
            get {
                return ResourceManager.GetString("Strings_LogModel_ParseFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing root file at {0}..
        /// </summary>
        internal static string Strings_LogModel_ParseRootFile {
            get {
                return ResourceManager.GetString("Strings_LogModel_ParseRootFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing safe control {0}..
        /// </summary>
        internal static string Strings_LogModel_ParseSafeControl {
            get {
                return ResourceManager.GetString("Strings_LogModel_ParseSafeControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing site definition {0}..
        /// </summary>
        internal static string Strings_LogModel_ParseSiteDefinition {
            get {
                return ResourceManager.GetString("Strings_LogModel_ParseSiteDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing site definitions from source project..
        /// </summary>
        internal static string Strings_LogModel_ParseSiteDefinitions {
            get {
                return ResourceManager.GetString("Strings_LogModel_ParseSiteDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing site definition schema at {0}..
        /// </summary>
        internal static string Strings_LogModel_ParseSiteDefinitionSchema {
            get {
                return ResourceManager.GetString("Strings_LogModel_ParseSiteDefinitionSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing template and root files from source project..
        /// </summary>
        internal static string Strings_LogModel_ParseTemplateAndRootFiles {
            get {
                return ResourceManager.GetString("Strings_LogModel_ParseTemplateAndRootFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing template file at {0}..
        /// </summary>
        internal static string Strings_LogModel_ParseTemplateFile {
            get {
                return ResourceManager.GetString("Strings_LogModel_ParseTemplateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing web temp file at {0}..
        /// </summary>
        internal static string Strings_LogModel_ParseWebTempFile {
            get {
                return ResourceManager.GetString("Strings_LogModel_ParseWebTempFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Strings_Wizard_CancelButton {
            get {
                return ResourceManager.GetString("Strings_Wizard_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the site, security level for debugging and the WSPBuilder project source.
        /// </summary>
        internal static string Strings_Wizard_DeploymentHeadline {
            get {
                return ResourceManager.GetString("Strings_Wizard_DeploymentHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicking this option means that users must have SharePoint administrator privileges to run or deploy the solution..
        /// </summary>
        internal static string Strings_Wizard_DeploymentLabelFullTrust {
            get {
                return ResourceManager.GetString("Strings_Wizard_DeploymentLabelFullTrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please see the Help topic &quot;Sandboxed Solution Considerations&quot; for more information..
        /// </summary>
        internal static string Strings_Wizard_DeploymentLabelHelp {
            get {
                return ResourceManager.GetString("Strings_Wizard_DeploymentLabelHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicking this option marks the solution as a sandboxed SharePoint solution, allowing any user to run or deploy the solution..
        /// </summary>
        internal static string Strings_Wizard_DeploymentLabelUserSolution {
            get {
                return ResourceManager.GetString("Strings_Wizard_DeploymentLabelUserSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What local site do you want to use for debugging?.
        /// </summary>
        internal static string Strings_Wizard_DeploymentLocalSiteQuestion {
            get {
                return ResourceManager.GetString("Strings_Wizard_DeploymentLocalSiteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy as a full-trust solution.
        /// </summary>
        internal static string Strings_Wizard_DeploymentRadioFullTrust {
            get {
                return ResourceManager.GetString("Strings_Wizard_DeploymentRadioFullTrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy as a sandboxed solution.
        /// </summary>
        internal static string Strings_Wizard_DeploymentRadioUserSolution {
            get {
                return ResourceManager.GetString("Strings_Wizard_DeploymentRadioUserSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the trust level for this SharePoint solution?.
        /// </summary>
        internal static string Strings_Wizard_DeploymentTrustLevelQuestion {
            get {
                return ResourceManager.GetString("Strings_Wizard_DeploymentTrustLevelQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        internal static string Strings_Wizard_DeploymentValidateButton {
            get {
                return ResourceManager.GetString("Strings_Wizard_DeploymentValidateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Strings_Wizard_FinishButton {
            get {
                return ResourceManager.GetString("Strings_Wizard_FinishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string Strings_Wizard_SourceBrowseButton {
            get {
                return ResourceManager.GetString("Strings_Wizard_SourceBrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio will import items from the specified deployable WSPBuilder project into a new SharePoint project..
        /// </summary>
        internal static string Strings_Wizard_VSeWSSImportSourceCaptionLabel {
            get {
                return ResourceManager.GetString("Strings_Wizard_VSeWSSImportSourceCaptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the new project source.
        /// </summary>
        internal static string Strings_Wizard_VSeWSSImportSourceHeadline {
            get {
                return ResourceManager.GetString("Strings_Wizard_VSeWSSImportSourceHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the path of the existing WSPBuilder project?.
        /// </summary>
        internal static string Strings_Wizard_VSeWSSImportSourcePathLabel {
            get {
                return ResourceManager.GetString("Strings_Wizard_VSeWSSImportSourcePathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WSPBuilder Converter Tool Extension Wizard.
        /// </summary>
        internal static string Strings_Wizard_WizardTitle {
            get {
                return ResourceManager.GetString("Strings_Wizard_WizardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid project name..
        /// </summary>
        internal static string Strings_WizardResouces_VSeWSSImportEmptyProjectName {
            get {
                return ResourceManager.GetString("Strings_WizardResouces_VSeWSSImportEmptyProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Not Installed..
        /// </summary>
        internal static string Strings_WizardResources_NoSharePointCaption {
            get {
                return ResourceManager.GetString("Strings_WizardResources_NoSharePointCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A SharePoint server is not installed on this computer. A SharePoint server must be installed to work with SharePoint projects..
        /// </summary>
        internal static string Strings_WizardResources_NoSharePointMessage {
            get {
                return ResourceManager.GetString("Strings_WizardResources_NoSharePointMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the site and choose a WSPBuilder project to continue..
        /// </summary>
        internal static string Strings_WizardResources_NotValid {
            get {
                return ResourceManager.GetString("Strings_WizardResources_NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error..
        /// </summary>
        internal static string Strings_WizardResources_ValidationErrorCaption {
            get {
                return ResourceManager.GetString("Strings_WizardResources_ValidationErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to the SharePoint site: {0}. {1}.
        /// </summary>
        internal static string Strings_WizardResources_ValidationErrorMessage {
            get {
                return ResourceManager.GetString("Strings_WizardResources_ValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection successful..
        /// </summary>
        internal static string Strings_WizardResources_ValidSiteUrlCaption {
            get {
                return ResourceManager.GetString("Strings_WizardResources_ValidSiteUrlCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully connected to SharePoint site {0}..
        /// </summary>
        internal static string Strings_WizardResources_ValidSiteUrlMessage {
            get {
                return ResourceManager.GetString("Strings_WizardResources_ValidSiteUrlMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read the project file &apos;{0}&apos;..
        /// </summary>
        internal static string Strings_WizardResources_VSeWSSImportUnableToReadProject {
            get {
                return ResourceManager.GetString("Strings_WizardResources_VSeWSSImportUnableToReadProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project creation cancelled..
        /// </summary>
        internal static string Strings_WizardResources_WizardCancelledMessage {
            get {
                return ResourceManager.GetString("Strings_WizardResources_WizardCancelledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create this template as a project..
        /// </summary>
        internal static string Strings_WizardResources_WizardMustBeItem {
            get {
                return ResourceManager.GetString("Strings_WizardResources_WizardMustBeItem", resourceCulture);
            }
        }
    }
}
